<?php
/**
 * AI Image Editor plugin for Craft CMS
 *
 * Edit images in the Craft CMS control panel using natural language, powered by AI.
 *
 * @link      https://www.spacecat.ninja
 * @copyright Copyright (c) 2026 André Elvan
 */

namespace spacecatninja\aiimageeditor\services;

use Craft;
use craft\base\Component;
use craft\elements\Asset;
use craft\helpers\Assets as AssetsHelper;
use craft\helpers\DateTimeHelper;
use craft\helpers\FileHelper;
use craft\helpers\StringHelper;

use spacecatninja\aiimageeditor\AiImageEditor;
use spacecatninja\aiimageeditor\events\SaveEvent;
use spacecatninja\aiimageeditor\exceptions\SessionException;
use spacecatninja\aiimageeditor\models\EditSession;
use spacecatninja\aiimageeditor\models\EditTurn;

use Throwable;
use yii\base\InvalidConfigException;

/**
 * The Finalize service turns an accepted edit session into a permanent asset.
 *
 * Finalizing is a two step process: first a finalize candidate is generated by
 * regenerating the last accepted working image at the configured final
 * resolution, then, after the user has compared before and after, the chosen
 * result is saved as a new asset in the source asset's folder.
 *
 * Note that the high resolution step is a generative regeneration, not a pixel
 * preserving upscale, which is why the comparison step exists.
 *
 * An instance of the service is available via `AiImageEditor::$plugin->getFinalize()`.
 *
 * @author André Elvan
 * @since 1.0.0
 */
class FinalizeService extends Component
{
    // Const Properties
    // =========================================================================

    /**
     * @event SaveEvent The event triggered before a result is saved as an
     * asset. Handlers may set fields on the asset or cancel the save.
     * @since 1.0.0
     */
    public const EVENT_BEFORE_SAVE = 'beforeSave';

    /**
     * @event SaveEvent The event triggered after a result is saved as an asset.
     * @since 1.0.0
     */
    public const EVENT_AFTER_SAVE = 'afterSave';

    /**
     * @var string The default prompt used for the finalize regeneration. Can
     * be overridden with the `finalizePrompt` setting.
     */
    public const DEFAULT_FINALIZE_PROMPT = 'Reproduce this exact image faithfully, at maximum resolution and quality. Do not change, add or remove anything in the image.';

    // Public Methods
    // =========================================================================

    /**
     * Generates the finalize candidate: one extra edit turn that regenerates
     * the last accepted working image at the final resolution.
     *
     * @param EditSession $session
     * @param string|null $resolution overrides the configured final resolution
     * @param string|null $outputFormat requested output format, forwarded so the candidate keeps the chosen format
     * @return array{result: \spacecatninja\aiimageeditor\models\EditResult, turn: EditTurn|null}
     * @throws SessionException if the session has no accepted turns, or its working image is gone
     * @throws InvalidConfigException if the session's driver is not registered
     *
     * @author André Elvan
     * @since 1.0.0
     */
    public function createFinalCandidate(EditSession $session, ?string $resolution = null, ?string $outputFormat = null): array
    {
        $sessions = AiImageEditor::$plugin?->getSessions();

        if ($sessions->getLatestTurn($session) === null) {
            throw new SessionException(Craft::t('ai-image-editor', 'There are no edits to finalize in this session.'));
        }

        $settings = AiImageEditor::$plugin?->getSettings();
        $driver = AiImageEditor::$plugin?->getDrivers()->getDriver($session->driverHandle);
        $prompt = $settings->finalizePrompt ?? self::DEFAULT_FINALIZE_PROMPT;
        $finalResolution = $resolution ?? $driver->getFinalResolution($session->model);

        return $sessions->runTurn(
            $session,
            $prompt,
            resolution: $finalResolution,
            isFinal: true,
            preserveContent: true,
            outputFormat: $outputFormat,
        );
    }

    /**
     * Saves the session's result, marks the session as finalized, and cleans
     * up its temporary files.
     *
     * By default the result is saved as a new asset in the source asset's
     * folder. Pass `$replaceOriginal = true` to replace the source asset's
     * file instead, keeping the asset (and its relations) intact. In both
     * cases the file gets a fresh `{basename}-edit-{timestamp}` filename.
     *
     * By default the latest finalize candidate is saved. Pass
     * `$useWorkingResolution = true` to save the last accepted working
     * resolution turn instead, the graceful fallback for when the high
     * resolution regeneration failed or drifted too far.
     *
     * @param EditSession $session
     * @param bool        $useWorkingResolution
     * @param bool        $replaceOriginal
     * @return Asset the created asset, or the source asset when replacing
     * @throws SessionException if there is no result to save, or the asset can't be created or replaced
     *
     * @author André Elvan
     * @since 1.0.0
     */
    public function saveResult(EditSession $session, bool $useWorkingResolution = false, bool $replaceOriginal = false): Asset
    {
        $sessions = AiImageEditor::$plugin?->getSessions();
        $turn = $sessions->getLatestTurn($session, !$useWorkingResolution);

        if ($turn === null && !$useWorkingResolution) {
            $turn = $sessions->getLatestTurn($session);
        }

        if ($turn === null) {
            throw new SessionException(Craft::t('ai-image-editor', 'There is no result to save in this session.'));
        }

        $resultPath = $sessions->getTurnImageLocalPath($session, $turn);

        if ($resultPath === null) {
            throw new SessionException(Craft::t('ai-image-editor', 'The result image no longer exists.'));
        }

        if ($session->isGeneration() && $replaceOriginal) {
            throw new SessionException(Craft::t('ai-image-editor', 'A generated image has no original to replace.'));
        }

        $extension = pathinfo($resultPath, PATHINFO_EXTENSION) ?: 'png';

        // saveElement() and replaceAssetFile() consume the temp file, so hand
        // them a copy and keep the session's own files intact until the
        // session is marked finalized.
        $tempPath = AssetsHelper::tempFilePath($extension);

        if (!copy($resultPath, $tempPath)) {
            throw new SessionException(Craft::t('ai-image-editor', 'The result image could not be prepared for saving.'));
        }

        if ($session->isGeneration()) {
            $folder = Craft::$app->getAssets()->getFolderById((int)$session->targetFolderId);

            if ($folder === null) {
                throw new SessionException(Craft::t('ai-image-editor', 'The target folder for this session no longer exists.'));
            }

            $filename = $this->_generateGenerationFilename($session, $extension, $resultPath);
        } else {
            $sourceAsset = $session->getSourceAsset();

            if ($sourceAsset === null) {
                throw new SessionException(Craft::t('ai-image-editor', 'The source asset for this session no longer exists.'));
            }

            try {
                $folder = $sourceAsset->getFolder();
            } catch (InvalidConfigException $invalidConfigException) {
                throw new SessionException(Craft::t('ai-image-editor', 'The source asset\'s folder could not be resolved.'), 0, $invalidConfigException);
            }

            $filename = $this->_generateFilename($sourceAsset, $extension);

            if ($replaceOriginal) {
                // Set before the replace, which saves the element, so
                // transforms are never generated against a stale center.
                $this->_applyDetectedFocalPoint($session, $sourceAsset, $resultPath);
                $this->_applyAiGeneratedFlag($sourceAsset);
                $this->_fireBeforeSave($session, $sourceAsset, true);

                try {
                    Craft::$app->getAssets()->replaceAssetFile($sourceAsset, $tempPath, $filename);
                } catch (Throwable $throwable) {
                    Craft::error("Could not replace the original asset file: {$throwable->getMessage()}", __METHOD__);

                    throw new SessionException(Craft::t('ai-image-editor', 'The original image could not be replaced.'), 0, $throwable);
                }

                $sessions->markFinalized($session, $sourceAsset->id);
                $this->_fireAfterSave($session, $sourceAsset, true);

                FileHelper::unlink($resultPath);

                return $sourceAsset;
            }
        }

        $asset = new Asset();
        $asset->tempFilePath = $tempPath;
        $asset->filename = $filename;
        $asset->newFolderId = $folder->id;
        $asset->setVolumeId($folder->volumeId);
        $asset->avoidFilenameConflicts = true;
        $asset->setScenario(Asset::SCENARIO_CREATE);

        $this->_applyDetectedFocalPoint($session, $asset, $resultPath);
        $this->_applyAiGeneratedFlag($asset);
        $this->_fireBeforeSave($session, $asset, false);

        try {
            $saved = Craft::$app->getElements()->saveElement($asset);
        } catch (Throwable $throwable) {
            Craft::error("Could not save the edited image as an asset: {$throwable->getMessage()}", __METHOD__);

            throw new SessionException(Craft::t('ai-image-editor', 'The edited image could not be saved as an asset.'), 0, $throwable);
        }

        if (!$saved) {
            Craft::error('Could not save the edited image as an asset: ' . implode(', ', $asset->getFirstErrors()), __METHOD__);

            throw new SessionException(Craft::t('ai-image-editor', 'The edited image could not be saved as an asset.'));
        }

        $sessions->markFinalized($session, $asset->id);
        $this->_fireAfterSave($session, $asset, false);

        FileHelper::unlink($resultPath);

        return $asset;
    }

    // Private Methods
    // =========================================================================

    /**
     * Fires the before-save event, letting handlers set fields on the asset or
     * cancel the save.
     *
     * @param EditSession $session
     * @param Asset       $asset
     * @param bool        $replace whether the source asset's file is being replaced
     * @throws SessionException if a handler cancels the save
     *
     * @author André Elvan
     * @since 1.0.0
     */
    private function _fireBeforeSave(EditSession $session, Asset $asset, bool $replace): void
    {
        if (!$this->hasEventHandlers(self::EVENT_BEFORE_SAVE)) {
            return;
        }

        $event = new SaveEvent(['session' => $session, 'asset' => $asset, 'replace' => $replace]);
        $this->trigger(self::EVENT_BEFORE_SAVE, $event);

        if (!$event->isValid) {
            throw new SessionException(Craft::t('ai-image-editor', 'The save was cancelled.'));
        }
    }

    /**
     * Fires the after-save event.
     *
     * @param EditSession $session
     * @param Asset       $asset
     * @param bool        $replace whether the source asset's file was replaced
     *
     * @author André Elvan
     * @since 1.0.0
     */
    private function _fireAfterSave(EditSession $session, Asset $asset, bool $replace): void
    {
        if (!$this->hasEventHandlers(self::EVENT_AFTER_SAVE)) {
            return;
        }

        $this->trigger(self::EVENT_AFTER_SAVE, new SaveEvent([
            'session' => $session,
            'asset' => $asset,
            'replace' => $replace,
        ]));
    }

    /**
     * Detects the focal point of the result image and sets it on the asset
     * before it's saved, so transforms are never generated against a stale
     * center point and later invalidated. Skipped when disabled, when the
     * asset already has a focal point, or when detection fails.
     */
    private function _applyDetectedFocalPoint(EditSession $session, Asset $asset, string $resultPath): void
    {
        $settings = AiImageEditor::$plugin?->getSettings();

        if (!($settings->autoFocalPoint ?? false) || $asset->getHasFocalPoint()) {
            return;
        }

        try {
            $focalPoint = AiImageEditor::$plugin?->getDrivers()
                ->getAnalysisDriver($session->driverHandle)
                ->detectFocalPoint($resultPath);
        } catch (Throwable $throwable) {
            Craft::warning("Focal point detection failed: {$throwable->getMessage()}", __METHOD__);

            return;
        }

        if ($focalPoint !== null) {
            $asset->setFocalPoint($focalPoint);
        }
    }

    /**
     * Switches on the configured "AI generated" field before the asset is
     * saved, so images edited or generated with AI can be marked, e.g. for
     * jurisdictions that require disclosure. What the field does with that is
     * left to the developer. No-op when the setting is unset or the field
     * isn't in the asset's field layout.
     */
    private function _applyAiGeneratedFlag(Asset $asset): void
    {
        $handle = AiImageEditor::$plugin?->getSettings()?->aiGeneratedField;

        if ($handle === null || $handle === '') {
            return;
        }

        $fieldLayout = $asset->getFieldLayout();

        if ($fieldLayout === null || $fieldLayout->getFieldByHandle($handle) === null) {
            Craft::warning("The configured aiGeneratedField \"{$handle}\" is not in the asset's field layout.", __METHOD__);

            return;
        }

        $asset->setFieldValue($handle, true);
    }

    /**
     * Generates the filename for a saved result:
     * `{original-basename}-edit-{timestamp}.{ext}`. An existing edit suffix is
     * replaced rather than stacked, so re-editing a result doesn't compound it.
     */
    private function _generateFilename(Asset $sourceAsset, string $extension): string
    {
        $basename = pathinfo($sourceAsset->getFilename(), PATHINFO_FILENAME);

        // Drop a prior edit suffix (also the legacy `-ai-edit-` form) so it
        // doesn't accumulate across successive edits. The 8+ digit run matches
        // our timestamp, not a short user-added counter like `-edit-3`.
        $basename = preg_replace('/-(?:ai-)?edit-\d{8,}$/', '', $basename) ?? $basename;

        return sprintf('%s-edit-%s.%s', $basename, DateTimeHelper::now()->format('YmdHis'), $extension);
    }

    /**
     * Generates the filename for a generated result. An AI description of the
     * image is preferred, falling back to the session's first prompt, and
     * finally to a generic timestamped name. Collisions are handled by the
     * asset's avoidFilenameConflicts flag.
     */
    private function _generateGenerationFilename(EditSession $session, string $extension, string $resultPath): string
    {
        $settings = AiImageEditor::$plugin?->getSettings();
        $slug = '';

        if ($settings->descriptiveFilenames ?? false) {
            try {
                $description = AiImageEditor::$plugin?->getDrivers()
                    ->getAnalysisDriver($session->driverHandle)
                    ->describeImage($resultPath);
            } catch (Throwable) {
                $description = null;
            }

            if ($description !== null) {
                $slug = FileHelper::sanitizeFilename(StringHelper::toKebabCase($description));
            }
        }

        if ($slug === '') {
            $turns = AiImageEditor::$plugin?->getSessions()->getTurns($session, false) ?? [];
            $prompt = $turns !== [] ? $turns[0]->prompt : '';
            $slug = FileHelper::sanitizeFilename(StringHelper::toKebabCase(StringHelper::safeTruncate($prompt, 40)));
        }

        if ($slug === '') {
            return sprintf('ai-image-%s.%s', DateTimeHelper::now()->format('YmdHis'), $extension);
        }

        return sprintf('%s.%s', $slug, $extension);
    }
}
